<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <AssemblyName>CoiCoop</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Mafi">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.dll</HintPath>
    </Reference>
    <Reference Include="Mafi.Core">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
